# Generated by Django 3.2 on 2021-05-12 18:27

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('locality', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=150)),
                ('descriptions', ckeditor.fields.RichTextField()),
                ('days_number', models.PositiveIntegerField()),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
