# Generated by Django 3.2 on 2021-05-14 08:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20210513_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='data_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='data_to',
            field=models.DateField(default=datetime.datetime(2021, 5, 14, 8, 7, 53, 482201, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
