# Generated by Django 3.2 on 2021-05-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20210514_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='total_rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
