# Generated by Django 3.2 on 2021-05-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_room_total_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='total_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
