# Generated by Django 3.2 on 2021-05-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_room_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_reservation',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room_reservation',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
