# Generated by Django 3.2 on 2021-05-18 10:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_auto_20210516_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room_reservation',
            old_name='Data_from',
            new_name='data_from',
        ),
        migrations.RemoveField(
            model_name='room',
            name='data_from',
        ),
        migrations.RemoveField(
            model_name='room',
            name='data_to',
        ),
        migrations.RemoveField(
            model_name='room_reservation',
            name='Data_to',
        ),
        migrations.AddField(
            model_name='room_reservation',
            name='data_to',
            field=models.DateField(default=datetime.datetime(2021, 5, 18, 10, 48, 3, 521108, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
