# Generated by Django 3.2 on 2021-06-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0018_alter_room_image_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room_reservation',
            options={'ordering': ['-id']},
        ),
    ]
