# Generated by Django 3.2 on 2021-06-29 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0020_auto_20210629_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rooms.place'),
            preserve_default=False,
        ),
    ]
