# Generated by Django 3.2 on 2021-07-01 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('rooms', '0022_room_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.place'),
        ),
        migrations.DeleteModel(
            name='place',
        ),
    ]
