# Generated by Django 3.2 on 2021-07-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0023_auto_20210701_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='total_rating',
        ),
    ]
