# Generated by Django 3.2 on 2021-07-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0024_remove_room_total_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='total_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
