# Generated by Django 3.2 on 2021-07-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0027_rename_total_rate_room_total_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='total_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
