# Generated by Django 3.2 on 2021-07-26 18:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0029_alter_room_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room_rating',
            unique_together={('user', 'room')},
        ),
    ]
