# Generated by Django 3.2 on 2021-07-08 12:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210708_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.png', upload_to=accounts.models.get_profile_image_filepath),
        ),
    ]
