# Generated by Django 3.2 on 2021-07-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='toggle_cart_option',
            field=models.BooleanField(default=False),
        ),
    ]
