# Generated by Django 3.2 on 2021-07-23 15:16

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_toggle_cart_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to=accounts.models.get_profile_image_filepath),
        ),
    ]
