# Generated by Django 3.2 on 2021-06-06 09:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='data_from',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='data_to',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 6, 6, 9, 53, 32, 813177, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
