# Generated by Django 3.2 on 2021-06-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_rename_country_tour_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='data_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='data_to',
            field=models.DateField(),
        ),
    ]
