# Generated by Django 3.2 on 2021-06-06 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20210606_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='tour/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_img', to='tours.tour')),
            ],
        ),
    ]
