# Generated by Django 3.2 on 2021-06-20 17:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0006_auto_20210607_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='tours.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
