# Generated by Django 3.2 on 2021-06-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tour_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_rating',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
