# Generated by Django 3.2 on 2021-06-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_tour_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='data_from',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='data_to',
            field=models.DateField(blank=True),
        ),
    ]
