# Generated by Django 3.2 on 2021-06-24 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_auto_20210624_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='data_from',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 6, 24, 9, 54, 34, 807816, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='data_to',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 6, 24, 9, 54, 45, 47064, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
