# Generated by Django 3.2 on 2021-07-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210727_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': 'Posts', 'verbose_name_plural': 'post'},
        ),
    ]
