# Generated by Django 3.2 on 2021-07-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Home_Cart',
        ),
    ]
