# Generated by Django 3.2 on 2021-07-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_cart_home_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_cart',
            name='title',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
