# Generated by Django 3.2 on 2021-07-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_home_cart_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='img',
            field=models.ImageField(default='', upload_to='places/'),
            preserve_default=False,
        ),
    ]
