# Generated by Django 3.2 on 2021-07-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_place_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Newsletter_Email',
                'verbose_name_plural': 'Newsletter_Emails',
            },
        ),
    ]
