# Generated by Django 3.2 on 2021-07-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_myfooter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyFooter',
            new_name='Info',
        ),
    ]
